server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://47.103.198.68:3306/cloud_user?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: whyhdm
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
  application:
    name: userservice
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

